### ISSUE TITLE
Highlight group generation breaks if bg or fg colors are not set

### ISSUE THREAD

**Issue by Slotos** [rafcamlet/tabline-framework.nvim#1]
highlights.lua's `set_hl` doesn't check for `fg` and `bg` values before extracting substrings for highlight group generation.

This breaks the plugin when color scheme doesn't set certain color value and no explicit color is supplied by the user. E.g. https://github.com/shaunsingh/nord.nvim

**Comment by rafcamlet** [comment]
@Slotos Thanks for pointing this out. :+1:
