### ISSUE TITLE
Basic example override default colors

### ISSUE THREAD

**Issue by ahmadie** [rafcamlet/tabline-framework.nvim#5]
```
local render = function(f)
  f.add '   '

  f.make_tabs(function(info)
    f.add(' ' .. info.index .. ' ')
    f.add(info.filename or '[no name]')
    f.add(info.modified and '+')
    f.add ' '
  end)
end
```
use this will overrite default colors, how can I not change default colors while applying above basice example

**Comment by rafcamlet** [comment]
Hi! Thanks for the issue!
Can you give an example of your whole setup?
This piece of code has nothing to do with the color settings, so it is very unlikely to be causing the problem.

The function `require ('tabline_framework').setup` has an option to override color settings.
https://github.com/rafcamlet/tabline-framework.nvim#configuration

Another possibility may be that you haven't been using the default color groups: TabLine, TabLineSel and TabLineFill until now. Please check if these groups are affected by use of tabline-framework.

**Comment by rafcamlet** [comment]
@ahmadie I'm closing this due to the lack of required information, but I will reopen if the problem still happening, and you could provide more info about it.
