### ISSUE TITLE
Error when i create new tab and open file

### ISSUE THREAD

**Issue by javeoff** [rafcamlet/tabline-framework.nvim#6]
Trouble steps:
> nvim
:tabnew
:e .
(select file and open)

Error may be, when i switching tabs (i think, it is a conflict with NvimTree)

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/62588539/156506234-423f5701-3f13-4452-b357-41bb1835b9a0.png">

**Comment by rafcamlet** [comment]
Hi @javeoff ! Thanks for your report! <3

The problem was actually related to reading options information from buffs. TF tried to read info from the discarded NvimTree buffer. The fix is already on the master. 👍

Have a nice day!
